check valid cluster names

diff --git a/bin/deploy-cluster b/bin/deploy-cluster
--- a/bin/deploy-cluster
+++ b/bin/deploy-cluster
@@ -34,14 +34,19 @@ date
 rm -fr .tmp.*
 if [ "$1" = tootsville.org ]
 then
-    echo "That seems dangerous/stupid. Let's not."
+    echo "That seems dangerous/stupid. Let's not." >&2
     exit 1
 fi
 if [ "x$1" = x ]
 then
-    echo "Cluster name required"
+    echo "Cluster name required" >&2
     exit 2
 fi
+grep "$1" << VALID_CLUSTERS || echo "Cluster name not recognized ($1)" >&2  && exit 2
+tootsville.org
+tootsville.ga
+tootsville.gc
+VALID_CLUSTERS
 
 cluster=$1
 
